services:
  rbmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672 # RabbitMQ Management UI
      - 5672:5672 # RabbitMQ AMQP protocol
    expose:
      - 5672
    # environment:
    #   RABBITMQ_DEFAULT_USER: user
    #   RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3

  mqtt:
    image: eclipse-mosquitto:1.6.15
    ports:
      - 1883:1883
    expose:
      - 1883

  task_worker:
    build:
      context: task_worker
      dockerfile: Dockerfile
    environment:
      RABBITMQ_HOST: rbmq
      REDIS_HOST: redis
      MQTT_HOST: mqtt
    depends_on:
      rbmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      mqtt:
        condition: service_started
    deploy:
      replicas: 1

  # router_bck:
  #   build:
  #     context: router
  #     dockerfile: Dockerfile
  #   environment:
  #     RABBITMQ_HOST: rbmq
  #     REDIS_HOST: redis
  #     MQTT_HOST: mqtt
  #   depends_on:
  #     rbmq:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #     mqtt:
  #       condition: service_started
  #   command: ./bck
  #   deploy:
  #     replicas: 1

  # router_fwd:
  #   build:
  #     context: router
  #     dockerfile: Dockerfile
  #   environment:
  #     RABBITMQ_HOST: rbmq
  #     REDIS_HOST: redis
  #     MQTT_HOST: mqtt
  #   depends_on:
  #     rbmq:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #     mqtt:
  #       condition: service_started
  #   command: ./fwd
  #   deploy:
  #     replicas: 1
